kaito-project/aikit

- .github/workflows/release.yaml
> ci: fix release verification

- .github/workflows/update-models.yaml
- README.md
> ci: fix update models

- pkg/aikit2llb/convert.go
> chore: update to localai v2.0.0

- .github/workflows/test-kubernetes.yaml
> ci: fix k8s test

- .github/workflows/extract-binary.yaml
> ci: extract binary from localai image

- README.md
- examples/llava.yaml
> docs: add llava to readme

- .github/workflows/pre-release.yaml
- .github/workflows/release.yaml
- .github/workflows/update-models.yaml
> ci: generate sbom and prov for aikit and pre-made model images

- README.md
- docs/cosign.md
> docs: image verification

- README.md
- docs/demo.md
> docs: update readme

- README.md
> docs: fix llava link

- .github/workflows/extract-binary.yaml
- pkg/aikit2llb/convert.go
> chore: update to localai v2.1.0

- .github/workflows/extract-binary.yaml
> ci: add input to extract binary

- .github/workflows/extract-binary.yaml
- pkg/aikit2llb/convert.go
> chore: update localai to 2.2.0

- pkg/aikit/config/specs_test.go
- pkg/aikit2llb/convert_test.go
- pkg/build/build.go
- pkg/build/build_test.go
> test: add basic tests

- .github/workflows/extract-binary.yaml
> ci: upload to blob store

- pkg/aikit2llb/convert.go
> chore: update to localai v2.3.1

- .github/workflows/update-models.yaml
- README.md
- models/mixtral-7x8b-instruct-cuda.yaml
- models/mixtral-7x8b-instruct.yaml
adds https://huggingface.co/TheBloke/Mixtral-8x7B-Instruct-v0.1-GGUF (Q4_K_M) to the pre-made models
Fixes #
> feat: add mixtral 8x7b

- pkg/aikit2llb/convert.go
> chore: update to localai v2.4.0

- README.md
> Update README with avx 

- .github/workflows/update-models.yaml
> ci: free space on update-models

- .github/workflows/update-models.yaml
> ci: free space on update-models take 2

- .github/workflows/update-models.yaml
> ci: doc update-image runner limitation

- pkg/aikit2llb/convert.go
> chore: update to localai v2.5.1

- README.md
> docs: update readme with table

- .github/workflows/test-docker-gpu.yaml
> test: add gpu agent

- .github/workflows/test-docker-gpu.yaml
- .github/workflows/test-docker.yaml
- .github/workflows/test-kubernetes.yaml
- pkg/aikit2llb/convert.go
> test: update gpu test

- .github/workflows/test-docker-gpu.yaml
> ci: change gpu test to matrix

- .github/workflows/patch-models.yaml
> ci: patch model images

- .github/workflows/patch-models.yaml
> ci: update patch models

- .github/workflows/test-docker.yaml
> ci: fix sd test

- pkg/aikit2llb/convert.go
> chore: update localai v2.6.0

- .github/workflows/release.yaml
- pkg/aikit2llb/convert.go
> ci: add gh release action

- .github/dependabot.yaml
> ci: group github actions for dependabot

- pkg/aikit2llb/convert.go
> chore: update localai v2.6.1

- .github/workflows/test-docker-gpu.yaml
- .github/workflows/test-docker.yaml
- .github/workflows/test-kubernetes.yaml
- pkg/aikit2llb/convert.go
- pkg/aikit2llb/image.go
- pkg/build/build.go
- pkg/utils/const.go
- test/aikitfile-mamba.yaml
> feat: add mamba backend

- .github/workflows/deploy-docs.yaml
> docs: reenable docs deploy

- website/docs/exllama.md
- website/docs/exllama2.md
- website/docs/llama-cpp.md
- website/docs/mamba.md
- website/docs/stablediffusion.md
- website/sidebars.js
> docs: add categories

- .github/workflows/lint.yaml
- .github/workflows/test-docker.yaml
- .github/workflows/test-kubernetes.yaml
- .github/workflows/unit-test.yaml
- website/sidebars.js
> ci: ignore website

- website/docusaurus.config.js
- website/src/css/custom.css
> docs: fix edit link

- .github/workflows/patch-models.yaml
> ci: fix copa patch conditionals

- README.md
- website/docs/intro.md
> docs: update misc

- .github/workflows/patch-models.yaml
> ci: fix copa patched tag

- .github/workflows/patch-models.yaml
> ci: use trivy binary for patch images

- .github/workflows/patch-models.yaml
- .github/workflows/update-models.yaml
> ci: update egress policy

- .github/workflows/test-docker.yaml
- .github/workflows/test-kubernetes.yaml
- .github/workflows/update-models.yaml
> ci: update egress for hf

- .github/workflows/update-models.yaml
> ci: update egress for deb

- .github/workflows/extract-binary.yaml
- pkg/aikit2llb/convert.go
> chore: update localai v2.8.2

- pkg/aikit2llb/convert.go
> chore: update localai v2.9.0

- .github/workflows/patch-models.yaml
> ci: add retry to trivy

- .github/workflows/test-finetune.yaml
> ci: finetune test

- .github/workflows/test-docker-gpu.yaml
- .github/workflows/test-finetune.yaml
> ci: don't fail on prune

- .github/workflows/pre-release.yaml
- .github/workflows/release.yaml
> ci: fix release ldflags

- .github/workflows/pre-release.yaml
> ci: prerelease enable push

- README.md
- website/docs/intro.md
> docs: update readme and website

- website/docs/fine-tune.md
- website/docs/intro.md
> docs: k8s finetune build

- website/docs/fine-tune.md
> docs: finetune update

- website/docs/demo.md
> docs: add finetune demo

- website/docusaurus.config.js
> docs: add announcement bar to website

- pkg/aikit2llb/inference/convert.go
> chore: bump localai v2.12.3

- website/docs/release.md
- website/sidebars.js
> docs: release process

- .github/workflows/patch-models.yaml
- .github/workflows/test-docker.yaml
- .github/workflows/test-kubernetes.yaml
- .github/workflows/update-models.yaml
- README.md
- models/llama-3-8b-instruct-cuda.yaml
- models/llama-3-8b-instruct.yaml
- pkg/aikit2llb/finetune/convert.go
- pkg/finetune/target_unsloth.py
- test/aikitfile-llama-cuda.yaml
- test/aikitfile-llama.yaml
- test/aikitfile-unsloth.yaml
- website/docs/premade-models.md
Signed-off-by: Sertac Ozercan <sozercan@gmail.com>
- adds llama3 8b instruct premade models
Fixes #
> feat: llama3 8b instruct pre-made model

- README.md
- website/docs/quick-start.md
> docs: update readme and quickstart with llama3

- .github/workflows/update-models-self.yaml
- .github/workflows/update-models.yaml
> ci: update self hosted update models

- .github/workflows/update-models-self.yaml
> ci: update models - disable mixtral

- .github/workflows/update-models-self.yaml
> ci: remove gha cache for update-models-self

- .github/workflows/test-docker-gpu.yaml
> test: update gpu test for llama3

- pkg/aikit2llb/finetune/convert.go
- pkg/finetune/target_unsloth.py
- test/aikitfile-unsloth.yaml
> feat: finetune llama3 support

- website/docs/premade-models.md
> docs: doc deprecated models

- website/docs/premade-models.md
> docs: fix new row in table

- .github/workflows/scorecards.yml
> fix: allow list api.scorecard.dev

- .github/workflows/test-docker-gpu.yaml
- pkg/aikit2llb/inference/convert.go
- pkg/aikit2llb/inference/image.go
instead of pulling from network, query local db
Fixes #
> fix: gpu detect

- Makefile
> fix: release pr workflow

- charts/aikit/Chart.yaml
> fix: chart appversion

- website/docs/kubernetes.md
> docs: helm chart

- demo/demo.sh
- models/llama-2-13b-chat.yaml
- models/llama-2-7b-chat.yaml
- models/llama-3-70b-instruct.yaml
- models/llama-3-8b-instruct.yaml
- models/mixtral-8x7b-instruct.yaml
- models/phi-3-3.8b.yaml
- pkg/aikit/config/inference_specs.go
- pkg/aikit/config/specs_test.go
- pkg/aikit2llb/inference/convert.go
- pkg/aikit2llb/inference/image.go
- pkg/build/build.go
- pkg/build/build_test.go
- pkg/utils/const.go
- test/aikitfile-exllama.yaml
- test/aikitfile-exllama2-exl2.yaml
- test/aikitfile-exllama2-gptq.yaml
- test/aikitfile-llama-cuda.yaml
- test/aikitfile-mamba.yaml
- test/aikitfile-stablediffusion.yaml
- test/aikitfile-unsloth-custom.yaml
- website/docs/gpu.md
- website/docs/specs-inference.md
> revert: runtime removal

- website/docs/llama-cpp.md
> docs: update llama.cpp

- .github/workflows/patch-models.yaml
- .github/workflows/update-models.yaml
- models/codestral-0.1-22b.yaml
> feat: add codestral

- website/docs/release.md
> docs: update release

- .github/workflows/release.yaml
> ci: allow helm.sh for release

- website/docusaurus.config.js
> docs: update baseUrl due to helm chart

- website/docs/kubernetes.md
> docs: helm repo

- README.md
- website/docs/llama-cpp.md
- website/docs/premade-models.md
> docs: gemma and codestral models

- README.md
- website/docs/create-images.md
- website/docs/intro.md
- website/docs/premade-models.md
- website/docs/quick-start.md
> docs: fix broken links

- README.md
- test/aikitfile-unsloth-custom.yaml
> fix: unsloth custom config

- .github/workflows/test-docker-args.yaml
- models/aikitfile.yaml
- test/aikitfile-args.yaml
> test: update args test

- .github/workflows/release-pr.yaml
> ci: remove push event from release-pr

- .github/workflows/release-pr.yaml
> ci: update release-pr push logic 

- .github/workflows/release-pr.yaml
> ci: fix release-pr push new version

- website/docusaurus.config.js
> chore: update website logo size

- demo/third_party/demo-magic/demo-magic.sh
> chore: update demo-magic.sh

- README.md
- website/docs/intro.md
> docs: update readme links

- demo/demo.sh
- models/codestral-22b.yaml
- models/gemma-2b-instruct.yaml
- models/llama-2-13b-chat.yaml
- models/llama-2-7b-chat.yaml
- models/llama-3-8b-instruct.yaml
- models/mixtral-8x7b-instruct.yaml
- models/phi-3-3.8b.yaml
- test/aikitfile-unsloth-custom.yaml
> chore: update prompt templates

- models/codestral-22b.yaml
> chore: update codestral hash

- .github/workflows/test-helm.yaml
- .github/workflows/test-kubernetes.yaml
- pkg/aikit2llb/inference/convert.go
- pkg/aikit2llb/inference/stablediffusion.go
blob store started returning 400 for some reason 🤷‍♂️
Fixes #
> chore: use cdn

- README.md
- website/docs/create-images.md
- website/docs/intro.md
> docs: arm64 docs

- README.md
- website/docs/quick-start.md
> docs: webui quick start

- .github/workflows/test-helm.yaml
- charts/aikit/templates/deployment.yaml
- charts/aikit/templates/namespace-post-install.yaml
- charts/aikit/values.yaml
- pkg/aikit2llb/inference/download.go
- website/docs/kubernetes.md
> feat: update helm pod security

- pkg/aikit2llb/finetune/convert.go
> chore: update unsloth to june2024

- .github/workflows/test-docker-args.yaml
- .github/workflows/update-models.yaml
- pkg/aikit2llb/inference/download.go
- pkg/build/args.go
- test/aikitfile-oci.yaml
- website/docs/create-images.md
> fix: drop gguf from ollama artifacts model name

- .github/workflows/test-docker-args.yaml
- .github/workflows/update-models.yaml
- pkg/aikit2llb/inference/download.go
- pkg/build/args.go
- test/aikitfile-oci.yaml
- website/docs/create-images.md
Signed-off-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Fixes #
> cherry pick #309

- .github/workflows/update-models-self.yaml
- .github/workflows/update-models.yaml
this is too big for the github agents now :( 
Fixes #
> chore: move codestral to self hosted update models

- .github/workflows/test-docker-gpu.yaml
> test: fix llama cuda test

- README.md
- website/docs/create-images.md
- website/docs/demo.md
- website/docs/fine-tune.md
- website/docs/gpu.md
- website/docs/intro.md
- website/docs/kubernetes.md
- website/docs/quick-start.md
- website/docs/stablediffusion.md
> docs: update demos

- website/sidebars.js
> docs: update sidebar

- .github/workflows/release-base.yaml
- Dockerfile.base
> ci: release base

- .github/workflows/release-base.yaml
> ci: fix base file

- .github/workflows/test-docker-args.yaml
> ci: fix source branch

- .github/workflows/test-docker-args.yaml
> ci: fix github repo for args test

- .github/workflows/test-docker-gpu.yaml
- pkg/aikit2llb/inference/convert.go
> chore: update localai to v2.19.1

- .github/workflows/patch-models.yaml
- .github/workflows/test-docker-args.yaml
- .github/workflows/test-docker.yaml
- .github/workflows/test-helm.yaml
- .github/workflows/test-kubernetes.yaml
- .github/workflows/update-models.yaml
> ci: add ubuntu to allow list

- README.md
- website/docs/premade-models.md
- website/docs/quick-start.md
> docs: update for llama3.1

- pkg/aikit2llb/inference/convert.go
> chore: cherry pick #343

- .github/workflows/patch-models.yaml
- .github/workflows/update-models.yaml
- README.md
- models/gemma-2-2b-instruct.yaml
- scripts/parse-models.sh
- website/docs/premade-models.md
> feat: add gemma2 2b

- .github/workflows/patch-models.yaml
- .github/workflows/update-models.yaml
- README.md
- models/gemma-2-2b-instruct.yaml
- scripts/parse-models.sh
- website/docs/premade-models.md
> chore: cherry-pick #355

- .github/workflows/patch-models.yaml
> ci: fix patch models

- README.md
- website/docs/premade-models.md
> docs: update flux emoji

- .github/workflows/update-models.yaml
> ci: fix flux release

- .github/workflows/pre-release.yaml
- .github/workflows/scorecards.yml
- .github/workflows/update-models.yaml
> ci: update allowlist

- website/docusaurus.config.js
> docs: add search

- .github/workflows/update-models.yaml
> ci: allow hf.co in update models

- pkg/aikit2llb/inference/image.go
> fix: set config file env

- pkg/aikit2llb/finetune/convert.go
- pkg/finetune/target_unsloth.py
- test/aikitfile-unsloth-custom.yaml
- test/aikitfile-unsloth.yaml
> chore: bump unsloth to sept-2024

- pkg/aikit2llb/inference/convert.go
> chore: bump localai v2.22.1

- Dockerfile.base
> chore: update base image chisel to 1.0.0 and use the new manifest

- .pre-commit-config.yaml
> ci: bump precommit

- README.md
- website/docs/create-images.md
- website/docs/gpu.md
> docs: update apple silicon docs

- .github/workflows/update-models.yaml
> ci: allow storage endpoint

- .github/workflows/update-models-self.yaml
- README.md
- models/qwq-32b-preview.yaml
- scripts/parse-models.sh
- website/docs/premade-models.md
> feat: add qwq 32b preview

- .github/workflows/update-models-self.yaml
- .github/workflows/update-models.yaml
- scripts/parse-models.sh
> ci: fix name parsing

- pkg/aikit2llb/inference/convert.go
> chore: bump localai v2.24.1

- .github/workflows/codeql.yml
- .github/workflows/lint.yaml
- .github/workflows/unit-test.yaml
- .golangci.yaml
> ci: bump golang 1.24

- .github/workflows/test-docker-gpu.yaml
> ci: gpu test inputs

- .github/workflows/test-helm.yaml
> ci: disable helm test for now

- .github/workflows/lint.yaml
- .github/workflows/patch-models.yaml
- .github/workflows/pre-release.yaml
- .github/workflows/release.yaml
> ci: allowlist *.githubusercontent.com

- website/osv-scanner.toml
> chore: ignore static website vulns for osv

- website/docusaurus.config.js
> update algolia search app

- website/docs/demo.md
> docs: update with flux demo

- website/docusaurus.config.js
> chore: add site verification

- website/docusaurus.config.js
> chore: update site verification

- website/docusaurus.config.js
> chore: update algolia index

- pkg/aikit2llb/inference/convert.go
> chore: update base

- .github/workflows/lint.yaml
- .github/workflows/test-docker-args.yaml
- .github/workflows/test-docker.yaml
- .github/workflows/test-kubernetes.yaml
- .github/workflows/unit-test.yaml
> test: test all the branches

- .github/workflows/patch-models.yaml
- .github/workflows/test-docker-args.yaml
- .github/workflows/test-docker.yaml
- .github/workflows/test-helm.yaml
- .github/workflows/test-kubernetes.yaml
- .github/workflows/update-models.yaml
> ci: use large runners

- .github/workflows/patch-models.yaml
- .github/workflows/test-docker-args.yaml
- .github/workflows/test-docker.yaml
- .github/workflows/test-helm.yaml
- .github/workflows/test-kubernetes.yaml
- .github/workflows/update-models.yaml
- Dockerfile.base
- README.md
- pkg/aikit2llb/inference/backend.go
- pkg/aikit2llb/inference/convert.go
- website/docs/intro.md
Signed-off-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Fixes #
> fix: cherry pick #618 #617

- website/docs/kubernetes.md
> Fix image repository version in Kubernetes docs

- Makefile
- charts/aikit/Chart.yaml
Signed-off-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
Fixes #
> revert: wrong version
